# Save only the latest 10 versions
# Not ready.
name: 删除过早的tag
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
# clone 本程序
      - name: checkout iotdb-daily-build
        uses: actions/checkout@v2
        with:
          path: iotdb-daily-build
          repository: 'xiaoyekanren/iotdb-daily-build'
          ref: master
          fetch-depth: 0
      - name: get tag list
        run: |
          cd ${{ github.workspace }}/iotdb-daily-build
# tag_list.txt --> 当前tag列表
          git tag > tag_list.txt
          all_line=$(cat tag_list.txt | wc -l)
# reserved_rows --> 要保留的tag数量
          reserved_rows=20
          if [ $reserved_rows > $all_line ]; then
               echo "tag共$all_line个，要删除$reserved_rows个，删除失败"
               exit 0
               exit 1
          fi
# tag_delete.txt --> 要删除的tag
          cat tag_list.txt | head -n `expr $all_line - $reserved_rows` > tag_delete.txt
          while read line
          do
              git tag -d ${line}
              git push origin :refs/tags/${line}
          done <　tag_delete.txt
# 保存历史
# git push commit
      - name: push commit
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}/iotdb-daily-build
          git config --local user.email "876670773+github-actions[bot]@qq.com"
          git config --local user.name "github-actions[bot]"
          cat tag_delete.txt >> history/deleted_tags.txt
          git add history/deleted_tags.txt
          git commit -m "$(date +"%Y-%m-%d") delete more tags."
          git push -u origin master
