name: Regularly delete redundant labels
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: collect common info
        run: |
          whoami
          uname -a