# Save only the latest 10 versions
# Not ready.
name: 删除过早的tag
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
# clone 本程序
      - name: checkout iotdb-daily-build
        uses: actions/checkout@v2
        with:
          path: iotdb-daily-build
          repository: 'xiaoyekanren/iotdb-daily-build'
          ref: master
          fetch-depth: 0
      - name: get tag list && push commit
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          program_path: ${{ github.workspace }}/iotdb-daily-build
        run: |
          cd ${program_path}
          /bin/bash ${program_path}/shell/tag_delete.sh

# git push commit
      - name: push commit
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}/iotdb-daily-build
          git config --local user.email "876670773+github-actions[bot]@qq.com"
          git config --local user.name "github-actions[bot]"
          cat tag_delete.txt >> history/deleted_tags.txt
          git add history/deleted_tags.txt
          git commit -m "$(date +"%Y-%m-%d") delete more tags."
          git push -u origin master

