name: test sshpass
on:
  workflow_dispatch:

jobs:
#--------
  check-commit:
    runs-on: ubuntu-latest
    steps:
# 下载iotdb
      - name: download iotdb
        run: | 
          wget https://github.com/apache/iotdb/releases/download/v0.12.6/apache-iotdb-0.12.6-server-bin.zip -O ${{ github.workspace }}/iotdb.zip
          du -sh ${{ github.workspace }}/iotdb.zip

# push iotdb
      - name: push iotdb to remote server
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
          host: ${{ secrets.IOTDBFUTURE_HOST }}
          port: ${{ secrets.IOTDBFUTURE_HOST_PORT }}
          username: ${{ secrets.IOTDBFUTURE_HOST_USER }}
          user_password: ${{ secrets.IOTDBFUTURE_HOST_USER_PASSWORD }}
          user_home: ${{ secrets.IOTDBFUTURE_HOST_USER_HOME }}
        run: |
          sudo sshpass -p '${user_password}' ssh ${username}@${host} -p ${port} whoami
          sudo sshpass -p '${user_password}' scp -P ${port} ${{ github.workspace }}/iotdb.zip ${username}@${host}:${user_home}/files/