# 轻易的不要执行这两步。。
# 清理10天以前 标记为"Draft"的release，一次只能删除30个
# 参考https://github.com/marketplace/actions/delete-draft-releases
name: tools 删除过早的tag 步骤2
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1
        with:
          threshold: 10d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
