name: iotdb 用户手册发布 v100
on:
#  push:
#    branches:
#      - master
  workflow_dispatch:

jobs:
#--------
  check-commit:
    runs-on: ubuntu-latest
    steps:
# get pandoc
      - name: get pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.19/pandoc-2.19-linux-amd64.tar.gz
          tar -zxvf pandoc-2.19-linux-amd64.tar.gz
# clone iotdb
      - name: checkout apache/iotdb
        uses: actions/checkout@v2
        with:
          path: iotdb
          repository: 'apache/iotdb'
          ref: 'rel/1.0'
          fetch-depth: 0
# clone 本程序
      - name: checkout iotdb-daily-build
        uses: actions/checkout@v2
        with:
          path: iotdb-daily-build
          repository: 'thulab/iotdb-daily-build'
          ref: master
          fetch-depth: 0
# generate
      - name: generate
        env:
          PYTHONPATH: ${{ github.workspace }}/iotdb-daily-build/program/UserGuide_Publish
        run: |
          export PATH=$PATH:${{ github.workspace }}/pandoc-2.19/bin
          cd ${{ github.workspace }}/iotdb/docs/zh/UserGuide
          doc_abs_path=`pwd`
          cd ${{ github.workspace }}/iotdb-daily-build/program/UserGuide_Publish
          python3 startup.py ${doc_abs_path}
          ls
          
          zip result.zip result.docx
          mv result.zip ${{ github.workspace }}/result.zip

      - name: collect common info
        shell: bash
        id: sys-info
        run: |
          cd ${{ github.workspace }}/iotdb
          echo "date=$(date +"%Y-%m-%d")" >> $GITHUB_OUTPUT
          echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#          echo "::set-output name=date::$(date +"%Y-%m-%d")"

      - name: Create UserGuide release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.sys-info.outputs.date }}-userguide-${{ steps.sys-info.outputs.commit_id }}
          release_name: ${{ steps.sys-info.outputs.date }} userguide ${{ steps.sys-info.outputs.commit_id }}
          body: null
          draft: false
          prerelease: false

      - name: Upload docs
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/result.zip
          asset_name: userguide-${{ steps.sys-info.outputs.date }}-${{ steps.sys-info.outputs.commit_id }}.zip
          asset_content_type: application/zip